apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend-app
spec:
  type: NodePort      # <--- IMPORTANT: Exposes the service externally
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 80        # The Service listens on port 80
      targetPort: 80  # The container is listening on port 80
